name: mantid-profiler
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build < 4
  - conda-verify
  - libmamba
  - libarchive
  - numpy
  - pre-commit
  - psutil
  - python-build
  - setuptools
  - toml
  - versioningit
  - wheel
