# load information from pyproject.toml
# change the build number by hand if you want to rebuild the package
schema_version: 1

context:
  version: ${{ load_from_file("../pyproject.toml").project.version }}
  build_number: 1

package:
  name: mantidprofiler
  version: ${{ version }}

source:
  path: ..

build:
  number: ${{ build_number }}
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python
    - setuptools>=42
    - wheel
  build:
    - setuptools>=42
  run:
    - python
    - argcomplete
    - psutil>=5.8.0
  run_constraints:
    - mantid>6.10 # only framework
tests:
  - python:
      imports:
        - mantidprofiler

about:
  license: ${{ load_from_file("../pyproject.toml").project.license.text }}
  license_file: LICENSE
  summary: ${{ load_from_file("../pyproject.toml").project.description }}
  homepage: ${{ load_from_file("../pyproject.toml").project.urls.homepage }}
